global:
  pattern: multitenant-cluster
  secretLoader:
      disabled: false
  # this turns on or off the network observability stack
  networkObservability: true
main:
  clusterGroupName: sno
  multiSourceConfig:
      enabled: true
      clusterGroupChartVersion: 0.9.*
