# This is a setup for the demonstration on a single node OpenShift cluster.

clusterGroup:
  name: sno
  isHubCluster: true
  namespaces:
  - open-cluster-management
  - vault
  - golang-external-secrets
  - cert-manager-operator
  - cert-manager
  - openshift-nfd
  - openshift-nmstate
  - openshift-storage
  - netobserv
  - metallb-system:
      operatorGroup: true
      targetNamespaces:
  - gitops-udn-a:
      labels:
        k8s.ovn.org/primary-user-defined-network: ""
        name: gitops-udn-a
  - gitops-udn-b:
      labels:
        k8s.ovn.org/primary-user-defined-network: ""
        name: gitops-udn-b
  - gitops-udn-c:
      labels:
        k8s.ovn.org/primary-user-defined-network: ""
        name: gitops-udn-c
  projects:
      - infra
      - vault
  subscriptions: 
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.14 # update as 2.15 is available
    cert-manager:
      name: openshift-cert-manager-operator
      namespace: cert-manager-operator
      channel: stable-v1
    # required for functional storage
    lvm-operator:
      name: lvms-operator
      namespace: openshift-storage
      source: redhat-operators
      channel: stable-4.19 # 4.20 is not available yet
    nfd:
      name: nfd
      namespace: openshift-nfd
      channel: stable

    metallb:
      name: metallb-operator
      namespace: metallb-system
      channel: stable
    nmstate:
      name: kubernetes-nmstate-operator
      namespace: openshift-nmstate
      channel: stable
    # network observability stack
    netobserv:
      name: netobserv-operator
      channel: stable
    loki:
      name: loki-operator
      channel: stable-6.3
  applications:

    # Do not install ACM until required 
    acm:
      name: acm
      namespace: open-cluster-management
      project: infra
      chart: acm
      chartVersion: 0.1.*
    vault:
      name: vault
      namespace: vault
      project: vault
      chart: hashicorp-vault
      chartVersion: 0.1.*
    secrets-operator:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: vault
      chart: golang-external-secrets
      chartVersion: 0.1.*
    lvm-storage:
      name: lvm-storage
      namespace: openshift-storage
      project: infra
      path: charts/infra/lvm-storage
    network-plumbing:
      name: network-plumbing
      namespace: openshift-nmstate
      project: infra
      path: charts/infra/network-plumbing
    netobserv:
      name: netobserv
      namespace: netobserv
      project: infra
      path: charts/infra/netobserv
  imperative:

    jobs:
    - name: install-deps
      playbook: ansible/install-deps.yaml
      verbosity: -vvv
      timeout: 3600
    # Use the script instead
    - name: networks
      playbook: ansible/enable-multinetworkpolicies.yaml
      verbosity: -vvv
      timeout: 1800
    # this doesn't work (permissions?)
    - name: set-default-storage-class
      playbook: ansible/set-default-storage-class.yaml
      verbosity: -vvv
      timeout: 1800
    clusterRoleYaml:

      - apiGroups:
          - "*"
        resources:
          - networks
          - storageclass
        verbs:
          - "*"
      - apiGroups:
          - "*"
        resources:
          - "*"
        verbs:
          - get
          - list
          - watch

    