---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: config-demo-secret
  namespace: netobserv
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: loki-s3
    template:
      type: Opaque
      data:
        bucketnames: {{ .Values.s3.bucket | quote }}
        endpoint: {{ printf "https://s3.%s.amazonaws.com" .Values.s3.region | quote }}
        region: {{ .Values.s3.region | quote }}
        access_key_id: {{ "{{ .aws_access_key_id | toString }}" | quote }}
        access_key_secret: {{ "{{ .aws_secret_access_key | toString }}" | quote }}
  data:
  - secretKey: aws_access_key_id 
    remoteRef:
      key: {{ .Values.awssecret.key }}
      property: aws_access_key_id
  - secretKey: aws_secret_access_key 
    remoteRef:
      key: {{ .Values.awssecret.key }}
      property: aws_secret_access_key